services:
  - type: web
    name: dharnesh-web-detection
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
